spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/invertir_ya_db
    username: postgres
    password: sistemas

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-2024-ba7f3732a33e.herokuapp.com/eureka/