spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/invertir_ya_db
    username: postgres
    password: sistemas
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-2024-ba7f3732a33e.herokuapp.com/eureka/
  instance:
    prefer-ip-address: true